services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: rzr_handshake
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - rzr_handshake_pgdata:/var/lib/postgresql/data

volumes:
  rzr_handshake_pgdata:
